services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - ${APP_DATA}/config:/config
      - ${APP_DATA}/cache:/cache
      - ${APP_DATA}/media:/media
